### ISSUE TITLE
Add 'Hover' Event Listener/Handler to Input Form

### ISSUE THREAD

**Issue by MJFoster** [the-sun-spots/solar-payoff#31]
On input form, specifically the **number of kWh field**, do the following:
- Listen for Hover State of mouse over an (i) image on the right edge
- Handle the event with a fadeIn() text box that explains to the user where they can locate their
  **DAILY Average** usage from their electric bill.
- Text should specify daily min/max (20/50 kWh) for user guidance.

**Comment by jessethach** [comment]
Jesse solved issue.
