### ISSUE TITLE
create estimate controller - estimateController.js

### ISSUE THREAD

**Issue by palindromed** [the-sun-spots/solar-payoff#9]
create estimateController.js

create object literal called estimateController

methods:

.incentiveBenefits() = this would call all other incentive calculating functions

.calcFederalBenefits() = any tax break not state specific

.calcUsageCredits() = calculate any usage credits

.calcStateBenefits() = was this made in WA? 

.calcTimeToPayOff() = how many months/years?? until home owner recoups initial investment

**Comment by jessethach** [comment]
Merged by Jesse
